#!/usr/bin/env bash
# scripts/android-dev.sh — one-command Android dev: sync + auth + `tauri android dev`,
# with the phone loading the app over the Tailscale Serve HTTPS URL.
#
# Usage: npm run android:dev:all              (inside nix-shell shell.android.nix,
#                                              phone connected via adb, on the tailnet)
#        npm run android:dev:all -- --print   resolve + print env, don't launch
#
# What it does:
#   1. Ensures Tailscale Serve proxies :5173 over HTTPS (enables it, tailnet-only,
#      if not already configured — persists until `tailscale serve --https=443 off`).
#   2. Exports VITE_ARCAN_ORIGIN + ALLOWED_ORIGINS to the Serve URL: the shell
#      derives auth, sync, and invite-link origins from it, and everything is
#      same-origin for the phone because Vite proxies /api and /sync.
#   3. Launches sync + auth via concurrently, plus `tauri android dev` with a
#      --config merge overriding build.devUrl so the phone's webview loads the
#      Serve URL (Tauri starts Vite itself via beforeDevCommand).
#
# Env-setup blocks are duplicated from scripts/dev-all.sh — keep them in sync.
set -euo pipefail

PRINT_ONLY=""
for arg in "$@"; do
  case "$arg" in
    --print) PRINT_ONLY=1 ;;
    *) echo "android-dev.sh: unknown argument: $arg (supported: --print)" >&2; exit 1 ;;
  esac
done

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

# Android toolchain guard — tauri android dev needs the SDK/NDK shell.
if [ -z "$PRINT_ONLY" ] && [ -z "${ANDROID_HOME:-}" ]; then
  echo "✗ ANDROID_HOME is not set — run inside: nix-shell shell.android.nix" >&2
  exit 1
fi

# Load project-local secrets / overrides (same mechanism as dev-all.sh).
if [ -f "$REPO_ROOT/.env.local" ]; then
  set -a
  # shellcheck disable=SC1091
  source "$REPO_ROOT/.env.local"
  set +a
fi

command -v tailscale >/dev/null 2>&1 || {
  echo "✗ tailscale CLI not found on PATH." >&2
  exit 1
}

serve_url() {
  tailscale serve status 2>/dev/null \
    | awk '/^https:\/\// {url=$1} /proxy http:\/\/(localhost|127\.0\.0\.1):5173/ {print url; exit}'
}

TS_SERVE_URL="$(serve_url)"
if [ -z "$TS_SERVE_URL" ]; then
  if [ -n "$PRINT_ONLY" ]; then
    echo "• Tailscale Serve is not proxying :5173 — a real run would enable it (tailnet-only)."
    exit 0
  fi
  echo "• Tailscale Serve not proxying :5173 yet — enabling (tailnet-only)…"
  tailscale serve --bg 5173
  TS_SERVE_URL="$(serve_url)"
fi
if [ -z "$TS_SERVE_URL" ]; then
  echo "✗ Could not resolve a Tailscale Serve HTTPS URL for :5173." >&2
  exit 1
fi
TS_SERVE_URL="${TS_SERVE_URL%/}"

# The shell derives auth, sync, and invite-link origins from this (spec §Server
# configuration); must match the origin the webview loads (devUrl below).
export VITE_ARCAN_ORIGIN="$TS_SERVE_URL"
# Unified: Vite server.allowedHosts + Better Auth trusted origins (see dev-all.sh).
export ALLOWED_ORIGINS="${ALLOWED_ORIGINS:-$TS_SERVE_URL}"
# Sync derives wss://<host>/sync/ from the origin → Vite's /sync proxy. An
# explicit VITE_SYNC_URL would defeat the Serve routing — ensure it's unset.
unset VITE_SYNC_URL

# Auth-server env (same defaults + secret pinning as dev-all.sh).
if [ -z "${BETTER_AUTH_SECRET:-}" ]; then
  BETTER_AUTH_SECRET="dev-$(head -c 24 /dev/urandom | base64 | tr -d /+=)"
  {
    echo ""
    echo "# Pinned dev auth secret — auto-generated by scripts/android-dev.sh."
    echo "# Deleting this logs out every dev user and orphans their accounts."
    echo "BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}"
  } >> "$REPO_ROOT/.env.local"
  export BETTER_AUTH_SECRET
  echo "• Pinned a new BETTER_AUTH_SECRET into .env.local (first run only)."
fi
export BETTER_AUTH_URL="${BETTER_AUTH_URL:-http://localhost:5173/api/auth}"
export AUTH_PORT="${AUTH_PORT:-4300}"
export AUTH_RATE_LIMIT_MAX="${AUTH_RATE_LIMIT_MAX:-1000}"
export AUTH_RATE_LIMIT_WINDOW="${AUTH_RATE_LIMIT_WINDOW:-60}"
export SYNC_HOST="${SYNC_HOST:-0.0.0.0}"
export SYNC_PORT="${SYNC_PORT:-4200}"

# devUrl override for the phone's webview, passed as a --config merge file
# (inline JSON quoting inside concurrently command strings is fragile).
# Stable gitignored path — overwritten every run, no temp-file leak.
DEV_CONFIG="$REPO_ROOT/node_modules/.tauri-android-dev.config.json"
printf '{"build":{"devUrl":"%s"}}\n' "$TS_SERVE_URL" > "$DEV_CONFIG"

DEVICE_LINE="$(command -v adb >/dev/null 2>&1 && adb devices | sed -n 2p || true)"

echo ""
echo "╭─── arcan android dev ───────────────────────────────────────"
echo "│  Phone loads:       ${TS_SERVE_URL}   (Tailscale Serve, HTTPS)"
echo "│  Auth + sync:       same-origin via Vite proxies (/api, /sync)"
echo "│  VITE_ARCAN_ORIGIN: ${VITE_ARCAN_ORIGIN}"
echo "│  Device:            ${DEVICE_LINE:-none detected (adb)}"
echo "╰──────────────────────────────────────────────────────────────"
echo ""

if [ -n "$PRINT_ONLY" ]; then
  echo "(--print: stopping before launch; devUrl override: $(cat "$DEV_CONFIG"))"
  exit 0
fi

exec npx --no-install concurrently \
  -k \
  -n "sync,auth,android" \
  -c "cyan,magenta,yellow" \
  --kill-others-on-fail \
  "npm run sync" \
  "PORT=${AUTH_PORT} npm run api" \
  "npx tauri android dev --config $DEV_CONFIG"
